import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:life_ops/services/db.dart';
import 'package:path_provider_platform_interface/path_provider_platform_interface.dart';
import 'package:plugin_platform_interface/plugin_platform_interface.dart';
import 'package:sqflite/sqflite.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

class _TempPathProvider extends PathProviderPlatform
    with MockPlatformInterfaceMixin {
  _TempPathProvider(this.dir);
  final String dir;
  @override
  Future<String?> getApplicationDocumentsPath() async => dir;
}

/// D-156: found live on the owner's own device — newsfeed_item rows
/// generated by earlier iterations of D-150/D-154/D-155's copy and item
/// types stuck around showing stale-format cards. Owner: "I would like
/// you to backfill the data in the cards that already exist for my
/// specific account. You do not need to make this a feature within the
/// app. This is a one time thing because it's only going to show up
/// during development." newsfeed_item is purely local SQLite (D-150:
/// "never sent anywhere"), so the only way to refresh it without device
/// access is a real schema migration that runs automatically, exactly
/// once, the one time a real device crosses the v12->v13 boundary.
void main() {
  final db = DatabaseHelper.instance;
  late Directory tempDir;

  setUpAll(() {
    TestWidgetsFlutterBinding.ensureInitialized();
    sqfliteFfiInit();
    databaseFactory = databaseFactoryFfi;
  });
  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('gp_newsfeed_backfill_test');
    PathProviderPlatform.instance = _TempPathProvider(tempDir.path);
  });
  tearDown(() async {
    if (tempDir.existsSync()) tempDir.deleteSync(recursive: true);
  });

  test('D-156: a newsfeed_item row from an existing v12 database is gone '
      'after upgrading to v13 — the actual migration, not just the SQL '
      'string', () async {
    // Simulate a real existing device: a v12 database, created
    // independently of DatabaseHelper's own _onCreate (which would also
    // create every other table this test doesn't need), with one stale
    // newsfeed row already in it.
    final path = '${tempDir.path}/LifeOps.db';
    final raw = await databaseFactory.openDatabase(
      path,
      options: OpenDatabaseOptions(
        version: 12,
        onCreate: (db, version) => DatabaseHelper.applyV12Schema(db),
      ),
    );
    await raw.insert(DatabaseHelper.newsfeedItemTable, {
      DatabaseHelper.columnNewsfeedType: 'essence',
      DatabaseHelper.columnNewsfeedTitle: 'stale title',
      DatabaseHelper.columnNewsfeedBody: 'stale body',
      DatabaseHelper.columnNewsfeedCreated: DateTime.now().toIso8601String(),
      DatabaseHelper.columnNewsfeedDedupeKey: 'essence-1',
    });
    final beforeUpgrade =
        await raw.query(DatabaseHelper.newsfeedItemTable);
    expect(beforeUpgrade, hasLength(1), reason: 'the stale row is really there');
    await raw.close();

    // The real app-launch path: DatabaseHelper opens the same file,
    // finds it at version 12, and runs the genuine v12->v13 _onUpgrade.
    final upgraded = await db.database;
    final rows = await upgraded.query(DatabaseHelper.newsfeedItemTable);
    expect(rows, isEmpty);
  });

  test('D-156: a fresh install (no existing database at all) is '
      'unaffected — there is nothing to wipe, and _onCreate never touches '
      'newsfeed_item beyond creating the empty table', () async {
    final rows = await (await db.database).query(DatabaseHelper.newsfeedItemTable);
    expect(rows, isEmpty);
  });

  test('D-157: upgrading from v13 removes type=article rows along the '
      'way — found live: a real article generated before the backend\'s '
      "markdown-code-fence parsing bug was fixed server-side consumed "
      "that day's dedupeKey, so only that row needed clearing to free "
      'the slot immediately rather than waiting until tomorrow. (This '
      "exercises the full migration chain to whatever the app's current "
      'version is, not an isolated v13->v14 hop in isolation — later '
      'migrations in the same chain also remove type=welcome (D-158) '
      'and type=essence (D-165), covered by their own tests below.)',
      () async {
    // Same schema as v12 (v13's own migration was a DELETE, not a
    // schema change), with one row of each type already in it.
    final path = '${tempDir.path}/LifeOps.db';
    final raw = await databaseFactory.openDatabase(
      path,
      options: OpenDatabaseOptions(
        version: 13,
        onCreate: (db, version) => DatabaseHelper.applyV12Schema(db),
      ),
    );
    for (final type in ['article', 'essence', 'streak', 'welcome']) {
      await raw.insert(DatabaseHelper.newsfeedItemTable, {
        DatabaseHelper.columnNewsfeedType: type,
        DatabaseHelper.columnNewsfeedTitle: '$type title',
        DatabaseHelper.columnNewsfeedBody: '$type body',
        DatabaseHelper.columnNewsfeedCreated: DateTime.now().toIso8601String(),
        DatabaseHelper.columnNewsfeedDedupeKey: '$type-key',
      });
    }
    await raw.close();

    final upgraded = await db.database;
    final rows = await upgraded.query(DatabaseHelper.newsfeedItemTable);
    final remainingTypes = rows.map((r) => r[DatabaseHelper.columnNewsfeedType]).toSet();

    expect(remainingTypes, {'streak'});
    expect(remainingTypes, isNot(contains('article')));
  });

  test('D-158: the v14->v15 migration deletes only type=welcome rows — '
      'clears the two welcome cards seeded under the old, adjacent-at-'
      "the-top spacing so they reseed correctly under D-158's fix. "
      '(This exercises the full migration chain to the current version, '
      'not an isolated v14->v15 hop — v15->v16/D-165 also removes '
      'type=essence in the same chain, covered by its own test below.)',
      () async {
    final path = '${tempDir.path}/LifeOps.db';
    final raw = await databaseFactory.openDatabase(
      path,
      options: OpenDatabaseOptions(
        version: 14,
        onCreate: (db, version) => DatabaseHelper.applyV12Schema(db),
      ),
    );
    for (final type in ['welcome', 'essence', 'streak', 'article']) {
      await raw.insert(DatabaseHelper.newsfeedItemTable, {
        DatabaseHelper.columnNewsfeedType: type,
        DatabaseHelper.columnNewsfeedTitle: '$type title',
        DatabaseHelper.columnNewsfeedBody: '$type body',
        DatabaseHelper.columnNewsfeedCreated: DateTime.now().toIso8601String(),
        DatabaseHelper.columnNewsfeedDedupeKey: '$type-key',
      });
    }
    await raw.close();

    final upgraded = await db.database;
    final rows = await upgraded.query(DatabaseHelper.newsfeedItemTable);
    final remainingTypes = rows.map((r) => r[DatabaseHelper.columnNewsfeedType]).toSet();

    expect(remainingTypes, {'streak', 'article'});
    expect(remainingTypes, isNot(contains('welcome')));
    expect(remainingTypes, isNot(contains('essence')));
  });

  test('D-165: the v15->v16 migration deletes only type=essence rows, '
      'leaving streak/article/welcome cards untouched — clears every '
      'essence card generated under the old flat "{cat}, redefined." '
      'template so they regenerate under the new first-definition/'
      'redefinition-aware framing', () async {
    final path = '${tempDir.path}/LifeOps.db';
    final raw = await databaseFactory.openDatabase(
      path,
      options: OpenDatabaseOptions(
        version: 15,
        onCreate: (db, version) => DatabaseHelper.applyV12Schema(db),
      ),
    );
    for (final type in ['essence', 'streak', 'article', 'welcome']) {
      await raw.insert(DatabaseHelper.newsfeedItemTable, {
        DatabaseHelper.columnNewsfeedType: type,
        DatabaseHelper.columnNewsfeedTitle: '$type title',
        DatabaseHelper.columnNewsfeedBody: '$type body',
        DatabaseHelper.columnNewsfeedCreated: DateTime.now().toIso8601String(),
        DatabaseHelper.columnNewsfeedDedupeKey: '$type-key',
      });
    }
    await raw.close();

    final upgraded = await db.database;
    final rows = await upgraded.query(DatabaseHelper.newsfeedItemTable);
    final remainingTypes = rows.map((r) => r[DatabaseHelper.columnNewsfeedType]).toSet();

    expect(remainingTypes, {'streak', 'article', 'welcome'});
    expect(remainingTypes, isNot(contains('essence')));
  });
}
