import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:life_ops/services/db.dart';
import 'package:path_provider_platform_interface/path_provider_platform_interface.dart';
import 'package:plugin_platform_interface/plugin_platform_interface.dart';
import 'package:sqflite/sqflite.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

class _TempPathProvider extends PathProviderPlatform
    with MockPlatformInterfaceMixin {
  _TempPathProvider(this.dir);
  final String dir;
  @override
  Future<String?> getApplicationDocumentsPath() async => dir;
}

/// D-156: found live on the owner's own device — newsfeed_item rows
/// generated by earlier iterations of D-150/D-154/D-155's copy and item
/// types stuck around showing stale-format cards. Owner: "I would like
/// you to backfill the data in the cards that already exist for my
/// specific account. You do not need to make this a feature within the
/// app. This is a one time thing because it's only going to show up
/// during development." newsfeed_item is purely local SQLite (D-150:
/// "never sent anywhere"), so the only way to refresh it without device
/// access is a real schema migration that runs automatically, exactly
/// once, the one time a real device crosses the v12->v13 boundary.
void main() {
  final db = DatabaseHelper.instance;
  late Directory tempDir;

  setUpAll(() {
    TestWidgetsFlutterBinding.ensureInitialized();
    sqfliteFfiInit();
    databaseFactory = databaseFactoryFfi;
  });
  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('gp_newsfeed_backfill_test');
    PathProviderPlatform.instance = _TempPathProvider(tempDir.path);
  });
  tearDown(() async {
    if (tempDir.existsSync()) tempDir.deleteSync(recursive: true);
  });

  test('D-156: a newsfeed_item row from an existing v12 database is gone '
      'after upgrading to v13 — the actual migration, not just the SQL '
      'string', () async {
    // Simulate a real existing device: a v12 database, created
    // independently of DatabaseHelper's own _onCreate (which would also
    // create every other table this test doesn't need), with one stale
    // newsfeed row already in it.
    final path = '${tempDir.path}/LifeOps.db';
    final raw = await databaseFactory.openDatabase(
      path,
      options: OpenDatabaseOptions(
        version: 12,
        onCreate: (db, version) => DatabaseHelper.applyV12Schema(db),
      ),
    );
    await raw.insert(DatabaseHelper.newsfeedItemTable, {
      DatabaseHelper.columnNewsfeedType: 'essence',
      DatabaseHelper.columnNewsfeedTitle: 'stale title',
      DatabaseHelper.columnNewsfeedBody: 'stale body',
      DatabaseHelper.columnNewsfeedCreated: DateTime.now().toIso8601String(),
      DatabaseHelper.columnNewsfeedDedupeKey: 'essence-1',
    });
    final beforeUpgrade =
        await raw.query(DatabaseHelper.newsfeedItemTable);
    expect(beforeUpgrade, hasLength(1), reason: 'the stale row is really there');
    await raw.close();

    // The real app-launch path: DatabaseHelper opens the same file,
    // finds it at version 12, and runs the genuine v12->v13 _onUpgrade.
    final upgraded = await db.database;
    final rows = await upgraded.query(DatabaseHelper.newsfeedItemTable);
    expect(rows, isEmpty);
  });

  test('D-156: a fresh install (no existing database at all) is '
      'unaffected — there is nothing to wipe, and _onCreate never touches '
      'newsfeed_item beyond creating the empty table', () async {
    final rows = await (await db.database).query(DatabaseHelper.newsfeedItemTable);
    expect(rows, isEmpty);
  });
}
