import 'dart:io';
import 'package:flutter/foundation.dart' show kDebugMode;
import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart' as intl;
import 'package:flutter/material.dart';

class DatabaseHelper {
  static const _databaseName = "LifeOps.db";
  static const _databaseVersion = 22; // 7: R3 schema — position, essences,
  // domain findings, account state (Part IV). 8: R6/D-062 — discards an
  // incomplete old-flow setup so the user starts the new Council setup
  // fresh instead of landing on a half-populated pyramid with no way back
  // into the (now-deleted) wizard. 9: D-123 — a habit's optional recurring
  // scheduled time and its native calendar event id. 10: D-124 — a
  // tasklog row's optional voice-transcribed miss reason. 11: D-123 — a
  // habit's own scheduled-event duration, in minutes. 12: D-150 — the
  // newsfeed_item table (personal, on-device newsfeed). 13: D-156 — a
  // one-time wipe of newsfeed_item, discarding rows generated by earlier
  // iterations of D-150/D-154/D-155's copy and item types before they
  // reached their current shape; generateNewItems() repopulates it fresh
  // from current data (and current logic) the next time anything touches
  // the newsfeed. 14: D-157 — a second, narrower one-time wipe: only
  // type='article' rows, discarding the one real article generated
  // before the backend's markdown-code-fence parsing bug was fixed
  // server-side, so the daily dedupeKey is free again immediately
  // rather than only tomorrow. 15: D-158 — a third, narrower one-time
  // wipe: only type='welcome' rows, discarding the two welcome cards
  // seeded (by D-156's own wipe, on the previous build) with the old,
  // adjacent-at-the-top timestamps, so they reseed with D-158's spacing
  // fix in effect the next time anything touches the newsfeed. 16:
  // D-165 — a fourth, narrower one-time wipe: only type='essence' rows,
  // discarding every essence card generated under the old flat
  // "{cat}, redefined." template so they all regenerate under the new
  // first-definition/redefinition-aware framing. 17: D-166 — collapses
  // consecutive same-text essence rows per category (phantom versions
  // manufactured by every past call to restoreFromCloud, before
  // insertCategoryEssence itself was guarded against no-op inserts) and
  // clears type='essence' newsfeed rows a second time so they
  // regenerate from the corrected history. 18: D-167 — a database-level
  // trigger (also created directly in applyV7Schema for a fresh
  // install) that silently rejects any insert into category_essence
  // that would duplicate the category's own current latest text — a
  // backstop against any future write path bypassing
  // insertCategoryEssence's own D-166 guard. 19: D-168 — retires the two
  // generic "welcome" newsfeed cards entirely (replaced by five sample
  // analysis-style cards with a subscribe pitch); deletes any existing
  // welcome-1/welcome-2 rows so they're gone for an account that already
  // had them. 20: D-168 (backfill) — an unconditional full wipe of
  // newsfeed_item, so every card on an existing account regenerates
  // fresh under everything the newsfeed accumulated across D-154
  // through D-168, not just whichever single round each prior narrow
  // migration targeted.

  // DEMO MODE FLAG
  static final ValueNotifier<bool> demoModeNotifier = ValueNotifier(false);
  static bool get isDemoMode => demoModeNotifier.value;
  static set isDemoMode(bool value) => demoModeNotifier.value = value;
  static void toggleDemoMode() =>
      demoModeNotifier.value = !demoModeNotifier.value;

  // Real tables
  static const taskTable = 'task';
  static const columnId = 'id';
  static const columnCategory = 'category';
  static const columnTaskDescription = 'taskdescription';
  static const columnSunday = 'sunday';
  static const columnMonday = 'monday';
  static const columnTuesday = 'tuesday';
  static const columnWednesday = 'wednesday';
  static const columnThursday = 'thursday';
  static const columnFriday = 'friday';
  static const columnSaturday = 'saturday';
  static const columnCreateDate = 'createdate';

  // D-123: a habit's optional recurring scheduled time. Null (the
  // default) means unscheduled — today's flexible, no-time behavior,
  // unchanged. 'HH:mm', 24-hour, local time — recurs on whichever of the
  // Sunday-Saturday flags above are already true, the same days the
  // habit is already active on; there is no separate day-of-week field
  // for scheduling. columnScheduledCalendarEventId is the native
  // calendar event's own id, kept so it can be updated or deleted later
  // without searching the calendar for it.
  static const columnScheduledTime = 'scheduledtime';
  static const columnScheduledCalendarEventId = 'scheduledcalendareventid';

  // D-123: how long the habit's scheduled block/native-calendar event
  // runs, in minutes. Null means "use the default" (15 minutes,
  // ScheduleHabitsScreen's own fallback) — set explicitly once the owner
  // taps a tray habit and chooses a duration. Applies whether or not the
  // habit is currently scheduled, so a duration chosen once survives an
  // unschedule/reschedule cycle rather than resetting to the default.
  static const columnScheduledDurationMinutes = 'scheduleddurationminutes';

  // The tasklog table. This stores the history of each task's
  // completion for each value.
  static const taskLogTable = 'tasklog';
  static const columnTLId = 'id';
  static const columnTLCategory = 'category';
  static const columnTLTaskDescription = 'taskdescription';
  static const columnTLChecked = 'checked';
  static const columnTLTaskDate = 'taskdate';

  // D-124: the voice-transcribed reason a scheduled habit's batch
  // check-in was answered "No" for — null on every row that was never
  // answered "No" from the check-in screen (including every row from
  // before this column existed).
  static const columnTLMissReason = 'missreason';

  // The quote table. This stores quotes displayed on the notification
  // response screen.
  static const quoteTable = 'quote';
  static const columnQuoteId = 'quoteid';
  static const columnQuoteText = 'quotetext';
  static const columnCurrent = 'current';

  // The category table. This stores the categories that tasks belong to.
  static const categoryTable = 'category';

  // --- R3 / Part IV additions -------------------------------------------
  // Pyramid slot, 1..6. Tier is derived: 1-3 foundational, 4-5 essential,
  // 6 peak. Replaces tier-implied-by-ordinal so D-051's drag-to-reorder is
  // expressible.
  static const columnPosition = 'position';
  static const columnCategoryCreated = 'created';

  // Versioned per-category essence (D-005, D-061). Keys on categoryid, not
  // the category name, so a rename cannot orphan it (D-084, II-N).
  static const categoryEssenceTable = 'category_essence';
  static const columnEssenceId = 'id';
  static const columnEssenceCategoryId = 'categoryid';
  static const columnEssenceText = 'essence';
  static const columnEssenceCreated = 'created';
  static const columnEssenceSourceSession = 'source_session_id';

  // D-150: the personal newsfeed — items generated entirely on-device from
  // the user's own existing data (streak milestones, essence changes),
  // never fetched from a server. dedupeKey is unique so re-running the
  // generator is always safe to call repeatedly (e.g. every newsfeed-screen
  // open) without ever inserting the same milestone twice.
  static const newsfeedItemTable = 'newsfeed_item';
  static const columnNewsfeedId = 'id';
  static const columnNewsfeedType = 'type';
  static const columnNewsfeedTitle = 'title';
  static const columnNewsfeedBody = 'body';
  static const columnNewsfeedCategoryId = 'categoryid';
  static const columnNewsfeedCreated = 'created';
  static const columnNewsfeedDedupeKey = 'dedupekey';

  // Accumulating four-domain findings (D-048).
  static const domainFindingTable = 'domain_finding';
  static const columnFindingId = 'id';
  static const columnFindingCategoryId = 'categoryid';
  static const columnFindingDomain = 'domain';
  static const columnFindingNote = 'note';
  static const columnFindingCreated = 'created';
  static const columnFindingSourceSession = 'source_session_id';

  static const Set<String> domains = {
    'biological',
    'psychological',
    'relational',
    'environmental'
  };

  // Single-row cache of server-authoritative entitlement (D-057). Never
  // authoritative itself: it can report a trial, never extend one.
  static const accountStateTable = 'account_state';
  static const columnAccountId = 'id';
  static const columnAccountUid = 'uid';
  static const columnEntitlement = 'entitlement';
  static const columnTrialStartedAt = 'trial_started_at';
  static const columnTrialExpiresAt = 'trial_expires_at';
  static const columnAccountTimezone = 'timezone';
  static const columnEntitlementSyncedAt = 'entitlement_synced_at';
  // D-178: single account-level personal-info fields, editable from the
  // Profile screen. columnProfilePhotoPath is a local file path only
  // (D-178: photo storage stays on-device for now, not cloud-backed) —
  // never synced to Firestore, unlike the other three.
  static const columnFirstName = 'first_name';
  static const columnEmail = 'email';
  static const columnPhone = 'phone';
  static const columnProfilePhotoPath = 'profile_photo_path';

  static const columnCategoryId = 'categoryid';
  static const columnCat = 'cat';

  // The chat_messages table. This stores full chat history with timestamps.
  static const chatTable = 'chat_messages';
  static const chatColumnId = 'id';
  static const chatColumnSender = 'sender';
  static const chatColumnContent = 'content';
  static const chatColumnTimestamp = 'timestamp';

  // The vision_statement table. This stores the user's vision statement.
  static const visionStatementTable = 'vision_statement';
  static const columnVisionId = 'id';
  static const columnVisionText = 'vision_text';
  static const columnVisionCreated = 'created';

  // The commentary_countdown table. This stores the remaining free commentary count.
  static const commentaryCountdownTable = 'commentary_countdown';
  static const columnCountdownId = 'id';
  static const columnCountdownValue = 'countdown_value';

  // Demo tables
  static const demoTaskTable = 'demo_task';
  static const demoTaskLogTable = 'demo_tasklog';
  static const demoCategoryTable = 'demo_category';
  static const demoQuoteTable = 'demo_quote';
  static const demoChatTable = 'demo_chat_messages';

  // Helper to get the correct table name
  String getTaskTable() => isDemoMode ? demoTaskTable : taskTable;
  String getTaskLogTable() => isDemoMode ? demoTaskLogTable : taskLogTable;
  String getCategoryTable() => isDemoMode ? demoCategoryTable : categoryTable;
  String getQuoteTable() => isDemoMode ? demoQuoteTable : quoteTable;
  String getChatTable() => isDemoMode ? demoChatTable : chatTable;

  // make this a singleton class
  DatabaseHelper._privateConstructor();

  static final DatabaseHelper instance = DatabaseHelper._privateConstructor();

  // only have a single app-wide reference to the database
  late Database _database;

  Future<Database> get database async {
    // lazily instantiate the db the first time it is accessed
    _database = await _initDatabase();
    return _database;
  }

  // this opens the database (and creates it if it doesn't exist)
  /// Set when the database cannot be opened or migrated (D-086). The app shows
  /// [DatabaseRecoveryScreen] instead of starting, rather than crashing or
  /// failing silently.
  static Object? openFailure;

  _initDatabase() async {
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String path = join(documentsDirectory.path, _databaseName);
    try {
      final db = await openDatabase(path,
          version: _databaseVersion,
          onCreate: _onCreate,
          onUpgrade: _onUpgrade);
      openFailure = null;
      return db;
    } catch (e, stack) {
      // D-086: migration is best-effort. A database we cannot open is not
      // silently discarded and does not crash the app — it is surfaced so the
      // user can be told plainly what to do.
      openFailure = e;
      if (kDebugMode) {
        print('DatabaseHelper: cannot open or migrate the database: $e');
        print(stack);
      }
      rethrow;
    }
  }

  /// The R3 schema additions (Part IV), written idempotently so the v7
  /// migration is safe to interrupt and retry (MIG-4). Shared by _onCreate
  /// and _onUpgrade so a fresh install and an upgraded install converge on
  /// exactly the same schema.
  static Future<void> applyV7Schema(Database db) async {
    // category.position — the pyramid slot. Added only if absent, because
    // ALTER TABLE ADD COLUMN is not idempotent.
    final cols = await db.rawQuery('PRAGMA table_info($categoryTable)');
    final names = cols.map((c) => c['name'] as String).toSet();
    if (!names.contains(columnPosition)) {
      await db.execute('ALTER TABLE $categoryTable '
          'ADD COLUMN $columnPosition INTEGER NOT NULL DEFAULT 0');
    }
    if (!names.contains(columnCategoryCreated)) {
      await db.execute(
          'ALTER TABLE $categoryTable ADD COLUMN $columnCategoryCreated TEXT');
    }

    // Backfill position from existing row order so every existing pyramid
    // renders identically (MIG-3). Only rows still at the 0 default are
    // touched, which keeps this safe to re-run.
    await db.execute(
        'UPDATE $categoryTable SET $columnPosition = $columnCategoryId '
        'WHERE $columnPosition = 0');

    await db.execute('CREATE TABLE IF NOT EXISTS $categoryEssenceTable ('
        '$columnEssenceId INTEGER PRIMARY KEY AUTOINCREMENT, '
        '$columnEssenceCategoryId INTEGER NOT NULL, '
        '$columnEssenceText TEXT NOT NULL, '
        '$columnEssenceCreated TEXT NOT NULL, '
        '$columnEssenceSourceSession TEXT)');
    await db.execute('CREATE INDEX IF NOT EXISTS idx_essence_cat_created ON '
        '$categoryEssenceTable ($columnEssenceCategoryId, $columnEssenceCreated DESC)');
    // D-167: a fresh install gets the duplicate-guard trigger from day
    // one — existing installs get it via the dedicated v17->v18
    // migration step below, since applyV7Schema only ever runs once, at
    // _onCreate or the original v6->v7 upgrade.
    await _createEssenceDuplicateGuardTrigger(db);

    await db.execute('CREATE TABLE IF NOT EXISTS $domainFindingTable ('
        '$columnFindingId INTEGER PRIMARY KEY AUTOINCREMENT, '
        '$columnFindingCategoryId INTEGER NOT NULL, '
        '$columnFindingDomain TEXT NOT NULL, '
        '$columnFindingNote TEXT NOT NULL, '
        '$columnFindingCreated TEXT NOT NULL, '
        '$columnFindingSourceSession TEXT)');
    await db.execute('CREATE INDEX IF NOT EXISTS idx_finding_cat ON '
        '$domainFindingTable ($columnFindingCategoryId)');

    // CHECK (id = 1) enforces the single-row invariant at the schema level.
    await db.execute('CREATE TABLE IF NOT EXISTS $accountStateTable ('
        "$columnAccountId INTEGER PRIMARY KEY CHECK ($columnAccountId = 1), "
        '$columnAccountUid TEXT, '
        "$columnEntitlement TEXT NOT NULL DEFAULT 'pre_trial', "
        '$columnTrialStartedAt TEXT, '
        '$columnTrialExpiresAt TEXT, '
        '$columnAccountTimezone TEXT, '
        '$columnEntitlementSyncedAt TEXT, '
        '$columnFirstName TEXT, '
        '$columnEmail TEXT, '
        '$columnPhone TEXT, '
        '$columnProfilePhotoPath TEXT)');
    await db.execute(
        'INSERT OR IGNORE INTO $accountStateTable ($columnAccountId) VALUES (1)');
  }

  /// D-150: the newsfeed_item table, written idempotently (MIG-4) so it's
  /// shared by _onCreate (fresh install) and the v12 _onUpgrade case
  /// (existing install) — same pattern applyV7Schema already established.
  static Future<void> applyV12Schema(Database db) async {
    await db.execute('CREATE TABLE IF NOT EXISTS $newsfeedItemTable ('
        '$columnNewsfeedId INTEGER PRIMARY KEY AUTOINCREMENT, '
        '$columnNewsfeedType TEXT NOT NULL, '
        '$columnNewsfeedTitle TEXT NOT NULL, '
        '$columnNewsfeedBody TEXT NOT NULL, '
        '$columnNewsfeedCategoryId INTEGER, '
        '$columnNewsfeedCreated TEXT NOT NULL, '
        '$columnNewsfeedDedupeKey TEXT NOT NULL, '
        'UNIQUE($columnNewsfeedDedupeKey))');
    await db.execute('CREATE INDEX IF NOT EXISTS idx_newsfeed_created ON '
        '$newsfeedItemTable ($columnNewsfeedCreated DESC)');
  }

  /// D-166: the v16->v17 migration's own cleanup — deletes every essence
  /// row whose text is identical to the immediately-preceding row (by
  /// [columnEssenceCreated]) for the same category, collapsing a
  /// "restored"-tagged run of phantom duplicate versions down to just
  /// its first occurrence. A genuine text change is never touched — only
  /// consecutive, byte-identical repeats. Static and pure-relative-to-`db`
  /// so it's directly testable against a raw database, matching this
  /// file's established migration-testing convention.
  static Future<void> _collapseDuplicateEssenceVersions(Database db) async {
    final rows = await db.query(categoryEssenceTable,
        orderBy: '$columnEssenceCategoryId ASC, $columnEssenceCreated ASC');
    final byCategory = <int, List<Map<String, dynamic>>>{};
    for (final row in rows) {
      final categoryId = row[columnEssenceCategoryId] as int;
      (byCategory[categoryId] ??= []).add(row);
    }
    final idsToDelete = <int>[];
    for (final categoryRows in byCategory.values) {
      String? previousText;
      for (final row in categoryRows) {
        final text = row[columnEssenceText] as String;
        if (text == previousText) {
          idsToDelete.add(row[columnEssenceId] as int);
        } else {
          previousText = text;
        }
      }
    }
    if (idsToDelete.isEmpty) return;
    final placeholders = List.filled(idsToDelete.length, '?').join(',');
    await db.delete(categoryEssenceTable,
        where: '$columnEssenceId IN ($placeholders)', whereArgs: idsToDelete);
  }

  /// D-167: a database-level backstop for the same invariant D-166's
  /// application-level guard enforces — belt and suspenders, at the
  /// owner's own explicit request after the phantom-duplicate defect
  /// ("ensure that there are guard rails in place to prevent this data
  /// condition from ever occurring again"). insertCategoryEssence is
  /// today the *only* code path that writes to [categoryEssenceTable]
  /// (confirmed directly against the source), so this trigger is not
  /// closing a currently-reachable gap — it exists so that no future
  /// code path (a new service method, a migration, a direct query) can
  /// silently reintroduce this exact data condition by writing to the
  /// table without going through the guarded helper. `RAISE(IGNORE)`
  /// inside a `BEFORE INSERT` trigger silently skips just that one insert
  /// (no exception raised, no partial transaction to clean up) — the same
  /// "no-op, not an error" contract `insertCategoryEssence`'s own
  /// `ConflictAlgorithm.ignore`-style guard already has, so a future
  /// caller that bypasses the Dart helper still gets safe, silent
  /// behavior rather than a crash.
  static Future<void> _createEssenceDuplicateGuardTrigger(Database db) async {
    await db.execute('''
      CREATE TRIGGER IF NOT EXISTS trg_no_duplicate_essence
      BEFORE INSERT ON $categoryEssenceTable
      WHEN NEW.$columnEssenceText = (
        SELECT $columnEssenceText FROM $categoryEssenceTable
        WHERE $columnEssenceCategoryId = NEW.$columnEssenceCategoryId
        ORDER BY $columnEssenceCreated DESC, $columnEssenceId DESC
        LIMIT 1
      )
      BEGIN
        SELECT RAISE(IGNORE);
      END;
    ''');
  }

  /// D-062: a user whose old-flow setup was incomplete when this build
  /// lands starts the new Council setup fresh, discarding their partial
  /// rows. "Complete" is six categories existing **and** at least one
  /// task existing — anything less is incomplete. A user who meets the
  /// definition is untouched (D-002, D-034). Runs once, gated by the
  /// version bump to 8, so it never re-triggers for an account created
  /// after this migration already ran.
  static Future<void> applyV8Migration(Database db) async {
    final categoryCount = Sqflite.firstIntValue(
            await db.rawQuery('SELECT COUNT(*) FROM $categoryTable')) ??
        0;
    final taskCount = Sqflite.firstIntValue(
            await db.rawQuery('SELECT COUNT(*) FROM $taskTable')) ??
        0;
    final complete = categoryCount >= 6 && taskCount >= 1;
    if (complete) return;

    // Never silent at the data layer, per D-062's acceptance criteria.
    print('D-062: incomplete old-flow setup found ($categoryCount '
        'categories, $taskCount tasks) — discarding partial rows, '
        'starting the new Council setup fresh.');

    await db.delete(taskTable);
    await db.delete(taskLogTable);
    await db.delete(categoryTable);
  }

  Future _onCreate(Database db, int version) async {
    // store the current version of a task
    try {
      await db.execute('''
            CREATE TABLE $taskTable (
              $columnId INTEGER PRIMARY KEY,
              $columnCategory TEXT NOT NULL,
              $columnTaskDescription TEXT NOT NULL,
              $columnSunday TEXT NOT NULL DEFAULT 'true',
              $columnMonday TEXT NOT NULL DEFAULT 'true',
              $columnTuesday TEXT NOT NULL DEFAULT 'true',
              $columnWednesday TEXT NOT NULL DEFAULT 'true',
              $columnThursday TEXT NOT NULL DEFAULT 'true',
              $columnFriday TEXT NOT NULL DEFAULT 'true',
              $columnSaturday TEXT NOT NULL DEFAULT 'true',
              $columnCreateDate TEXT NOT NULL,
              $columnScheduledTime TEXT,
              $columnScheduledCalendarEventId TEXT,
              $columnScheduledDurationMinutes INTEGER,
              UNIQUE($columnCategory, $columnTaskDescription)
            )
            ''');
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }

    // store the history of task executions
    try {
      await db.execute('''
            CREATE TABLE $taskLogTable (
              $columnTLId INTEGER PRIMARY KEY,
              $columnTLCategory TEXT NOT NULL,
              $columnTLTaskDescription TEXT NOT NULL,
              $columnTLChecked TEXT NOT NULL,
              $columnTLTaskDate TEXT NOT NULL,
              $columnTLMissReason TEXT,
              UNIQUE($columnTLCategory, $columnTLTaskDescription, $columnTLTaskDate)
            )
            ''');
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }

    try {
      await db.execute('''
            CREATE TABLE $categoryTable (
              $columnCategoryId INTEGER PRIMARY KEY,
              $columnCat TEXT NOT NULL,
              UNIQUE($columnCat) ON CONFLICT IGNORE
            )
            ''');
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }

    // store quotes
    try {
      await db.execute('''
            CREATE TABLE $quoteTable (
              $columnQuoteId INTEGER PRIMARY KEY,
              $columnQuoteText TEXT NOT NULL,
              $columnCurrent TEXT NOT NULL
            )
            ''');
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }

    try {
      await db.execute('''
          CREATE INDEX curr_index ON $quoteTable($columnCurrent)
            ''');
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }

    try {
      await db.execute('''
        CREATE TABLE $chatTable (
          $chatColumnId INTEGER PRIMARY KEY AUTOINCREMENT,
          $chatColumnSender TEXT NOT NULL,
          $chatColumnContent TEXT NOT NULL,
          $chatColumnTimestamp TEXT NOT NULL
        )
        ''');
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }

    try {
      await db.execute('''
            CREATE TABLE $visionStatementTable (
              $columnVisionId INTEGER PRIMARY KEY AUTOINCREMENT,
              $columnVisionText TEXT NOT NULL,
              $columnVisionCreated TEXT NOT NULL
            )
            ''');
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }

    // Commentary countdown table
    try {
      await db.execute('''
            CREATE TABLE $commentaryCountdownTable (
              $columnCountdownId INTEGER PRIMARY KEY,
              $columnCountdownValue INTEGER NOT NULL
            )
            ''');
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }

    // DEMO TABLES
    await db.execute('''
          CREATE TABLE IF NOT EXISTS $demoTaskTable (
            $columnId INTEGER PRIMARY KEY,
            $columnCategory TEXT NOT NULL,
            $columnTaskDescription TEXT NOT NULL,
            $columnSunday TEXT NOT NULL DEFAULT 'true',
            $columnMonday TEXT NOT NULL DEFAULT 'true',
            $columnTuesday TEXT NOT NULL DEFAULT 'true',
            $columnWednesday TEXT NOT NULL DEFAULT 'true',
            $columnThursday TEXT NOT NULL DEFAULT 'true',
            $columnFriday TEXT NOT NULL DEFAULT 'true',
            $columnSaturday TEXT NOT NULL DEFAULT 'true',
            $columnCreateDate TEXT NOT NULL,
            $columnScheduledTime TEXT,
            $columnScheduledCalendarEventId TEXT,
              $columnScheduledDurationMinutes INTEGER,
            UNIQUE($columnCategory, $columnTaskDescription)
          )
          ''');
    await db.execute('''
          CREATE TABLE IF NOT EXISTS $demoTaskLogTable (
            $columnTLId INTEGER PRIMARY KEY,
            $columnTLCategory TEXT NOT NULL,
            $columnTLTaskDescription TEXT NOT NULL,
            $columnTLChecked TEXT NOT NULL,
            $columnTLTaskDate TEXT NOT NULL,
            $columnTLMissReason TEXT,
            UNIQUE($columnTLCategory, $columnTLTaskDescription, $columnTLTaskDate)
          )
          ''');
    await db.execute('''
          CREATE TABLE IF NOT EXISTS $demoCategoryTable (
            $columnCategoryId INTEGER PRIMARY KEY,
            $columnCat TEXT NOT NULL,
            UNIQUE($columnCat) ON CONFLICT IGNORE
          )
          ''');
    await db.execute('''
          CREATE TABLE IF NOT EXISTS $demoQuoteTable (
            $columnQuoteId INTEGER PRIMARY KEY,
            $columnQuoteText TEXT NOT NULL,
            $columnCurrent TEXT NOT NULL
          )
          ''');
    await db.execute('''
          CREATE TABLE IF NOT EXISTS $demoChatTable (
            $chatColumnId INTEGER PRIMARY KEY AUTOINCREMENT,
            $chatColumnSender TEXT NOT NULL,
            $chatColumnContent TEXT NOT NULL,
            $chatColumnTimestamp TEXT NOT NULL
          )
          ''');

    // R3 / Part IV schema, shared with the v7 migration.
    await applyV7Schema(db);
    // D-150: the newsfeed table, shared with the v12 migration.
    await applyV12Schema(db);
  }

  Future _onUpgrade(Database db, int oldVersion, int newVersion) async {
    for (var i = oldVersion; i <= newVersion; i++) {
      if (i > oldVersion) {
        switch (i) {
          case 2:
            if (kDebugMode) {
              print(
                  '****** in _onUpgrade(): oldversion is $oldVersion and newVersion is $newVersion');
            }
            await db.execute(
                "ALTER TABLE task ADD COLUMN sunday TEXT NOT NULL DEFAULT 'true'");
            await db.execute(
                "ALTER TABLE task ADD COLUMN monday TEXT NOT NULL DEFAULT 'true'");
            await db.execute(
                "ALTER TABLE task ADD COLUMN tuesday TEXT NOT NULL DEFAULT 'true'");
            await db.execute(
                "ALTER TABLE task ADD COLUMN wednesday TEXT NOT NULL DEFAULT 'true'");
            await db.execute(
                "ALTER TABLE task ADD COLUMN thursday TEXT NOT NULL DEFAULT 'true'");
            await db.execute(
                "ALTER TABLE task ADD COLUMN friday TEXT NOT NULL DEFAULT 'true'");
            await db.execute(
                "ALTER TABLE task ADD COLUMN saturday TEXT NOT NULL DEFAULT 'true'");
            break;
          case 3:
            if (kDebugMode) {
              print(
                  '****** in _onUpgrade(): oldversion is $oldVersion and newVersion is $newVersion');
            }
            await db.execute('''
              CREATE TABLE $chatTable (
              $chatColumnId INTEGER PRIMARY KEY AUTOINCREMENT,
              $chatColumnSender TEXT NOT NULL,
              $chatColumnContent TEXT NOT NULL,
              $chatColumnTimestamp TEXT NOT NULL
            )
            ''');
          case 4:
            if (kDebugMode) {
              print('****** in _onUpgrade(): oldversion is '
                  ' 2$oldVersion and newVersion is $newVersion');
            }
            await db.execute('''
              CREATE TABLE $visionStatementTable (
                $columnVisionId INTEGER PRIMARY KEY AUTOINCREMENT,
                $columnVisionText TEXT NOT NULL,
                $columnVisionCreated TEXT NOT NULL
              )
            ''');
          case 5:
            if (kDebugMode) {
              print('****** in _onUpgrade(): oldversion is '
                  ' 2$oldVersion and newVersion is $newVersion');
            }
            await db.execute('''
              CREATE TABLE $commentaryCountdownTable (
                $columnCountdownId INTEGER PRIMARY KEY,
                $columnCountdownValue INTEGER NOT NULL
              )
            ''');
            break;
          case 7:
            // R3 / Part IV. Idempotent (MIG-4): safe to interrupt and retry.
            // sqflite runs onUpgrade in a transaction, so a failure here
            // leaves the database at version 6 and the app fully functional.
            await applyV7Schema(db);
            break;
          case 8:
            // D-062: runs once, after v7 is guaranteed present above.
            await applyV8Migration(db);
            break;
          case 9:
            // D-123: a habit's optional recurring scheduled time, and the
            // id of the native calendar event it wrote (if any) — both
            // null on every existing row, matching the unscheduled
            // default a fresh install already gets from v9's CREATE TABLE.
            await db.execute(
                'ALTER TABLE $taskTable ADD COLUMN $columnScheduledTime TEXT');
            await db.execute(
                'ALTER TABLE $taskTable ADD COLUMN $columnScheduledCalendarEventId TEXT');
            break;
          case 10:
            // D-124: a tasklog row's optional voice-transcribed miss
            // reason — null on every existing row, matching the "never
            // answered No from the check-in screen" default a fresh
            // install already gets from v10's CREATE TABLE.
            await db.execute(
                'ALTER TABLE $taskLogTable ADD COLUMN $columnTLMissReason TEXT');
            break;
          case 11:
            // D-123: a habit's own scheduled-event duration — null on
            // every existing row, matching the "use the default" behavior
            // a fresh install already gets from v11's CREATE TABLE.
            await db.execute(
                'ALTER TABLE $taskTable ADD COLUMN $columnScheduledDurationMinutes INTEGER');
            break;
          case 12:
            // D-150: the newsfeed_item table — a brand-new table, so
            // idempotent CREATE TABLE IF NOT EXISTS is enough (no ALTER
            // TABLE backfill needed, unlike the column additions above).
            await applyV12Schema(db);
            break;
          case 13:
            // D-156: a one-time wipe of every existing newsfeed_item row
            // — found live, an existing install (specifically the one
            // this was developed and tested on) had accumulated rows
            // from D-150/D-154/D-155's copy and item-type iterations
            // before they reached their current shape, so the newsfeed
            // kept showing stale-format cards until data was pulled in
            // some other way. Nothing here regenerates content directly
            // — the very next call to NewsfeedService.generateNewItems()
            // (the newsfeed screen opening, a task check-off, an essence
            // edit) repopulates the table fresh, against current data
            // and current logic. Owner: "You do not need to make this a
            // feature within the app. This is a one time thing because
            // it's only going to show up during development" — this
            // migration only ever runs once, the single time a real
            // device crosses the v12->v13 boundary, never again after.
            await db.delete(newsfeedItemTable);
            break;
          case 14:
            // D-157: found live — the very first real article a
            // subscribed account generated came back wrapped in a
            // ```json code fence, which the backend's JSON.parse choked
            // on, falling back to the generic "Your Pyramid, Analyzed"
            // headline with the raw fenced text dumped into the body.
            // Fixed server-side (parseArticleReply now strips a fence
            // before parsing), but that one broken row already consumed
            // today's daily dedupeKey ('article-<date>'), so it would
            // otherwise sit there until tomorrow. Deleting only
            // type='article' rows (not the whole table, unlike D-156 —
            // the essence/streak/welcome cards D-156 just regenerated
            // are fine and untouched) frees the slot immediately.
            await db.delete(newsfeedItemTable,
                where: '$columnNewsfeedType = ?', whereArgs: ['article']);
            break;
          case 15:
            // D-158: found live — the two welcome cards, seeded
            // back-to-back with near-identical timestamps, landed right
            // next to each other at the top of the feed. Fixed in
            // NewsfeedService._seedWelcomeCards (deliberate, permanent
            // timestamp placement instead of "now" for both), but the
            // two rows already on-device were seeded under the old
            // logic. Deleting only type='welcome' rows — not the whole
            // table — lets them reseed correctly on next use, leaving
            // every real essence/streak/article card untouched.
            await db.delete(newsfeedItemTable,
                where: '$columnNewsfeedType = ?', whereArgs: ['welcome']);
            break;
          case 16:
            // D-165: found live — every essence-redefinition card, no
            // matter how many times a category's essence had actually
            // been redefined, rendered the exact same flat template
            // ("{cat}, redefined." + "Here's what {cat} means to you
            // now:"), with no distinction between a category's first
            // definition and a later change, and no acknowledgment of
            // what changed or when. _generateEssenceItems now frames a
            // first definition and a redefinition as genuinely different
            // events (the latter naming how long the previous version
            // held). Deleting only type='essence' rows — not the whole
            // table — lets every existing essence version regenerate
            // under the new framing the next time anything touches the
            // newsfeed, leaving streak/article/welcome cards untouched.
            await db.delete(newsfeedItemTable,
                where: '$columnNewsfeedType = ?', whereArgs: ['essence']);
            break;
          case 17:
            // D-166: found live, on the owner's own account — a category
            // showed 7 essence "versions" in a row, all identical text,
            // none of them an actual redefinition. Root cause:
            // SyncService.restoreFromCloud called insertCategoryEssence
            // unconditionally on every restore, manufacturing a
            // brand-new version identical to the existing one purely as
            // a side effect of syncing (this session's many OTA
            // reinstalls each triggered a restore via D-137). Fixed at
            // the source: insertCategoryEssence (this same change) is
            // now a no-op when the new text matches the category's
            // current latest version, so this can't recur. This
            // one-time cleanup collapses every existing run of
            // consecutive same-text essence rows per category down to
            // just the first occurrence, keeping every row that
            // represents a genuine change. type='essence' newsfeed rows
            // are cleared again so they regenerate from the now-
            // corrected history. (Firestore's own essenceVersions
            // collection isn't touched by this on-device migration —
            // nothing at runtime reads it back — but the owner directly
            // pointed out that leaving it full of the same phantom
            // duplicates still *looks* broken when inspected. Cleaned
            // separately, once, via a one-time admin script against the
            // one real account on this project — not something every
            // device's migration needs to repeat.)
            await _collapseDuplicateEssenceVersions(db);
            await db.delete(newsfeedItemTable,
                where: '$columnNewsfeedType = ?', whereArgs: ['essence']);
            break;
          case 18:
            // D-167: a database-level backstop for the same invariant —
            // owner: "ensure that there are guard rails in place to
            // prevent this data condition from ever occurring again."
            // insertCategoryEssence (D-166) already guards the only
            // current write path; this trigger means no *future* write
            // path can silently reintroduce the same defect either.
            await _createEssenceDuplicateGuardTrigger(db);
            break;
          case 19:
            // D-168: the two generic "welcome" newsfeed cards are
            // retired entirely, replaced by five sample analysis-style
            // cards each carrying a subscribe pitch (NewsfeedService
            // no longer generates type='welcome' at all). Deletes any
            // existing welcome-1/welcome-2 rows so they disappear for
            // an account that already had them; the next touch of the
            // newsfeed seeds the five sample cards fresh in their
            // place, the same self-limiting trigger pattern D-158
            // established.
            await db.delete(newsfeedItemTable,
                where: '$columnNewsfeedType = ?', whereArgs: ['welcome']);
            break;
          case 20:
            // D-168 (backfill): owner — "I also need you to clean up my
            // database because I still have cards in there that were
            // generated before this change." D-156/D-157/D-158/D-165's
            // own migrations each narrowly wiped one card type at the
            // moment its own copy/logic changed; by this point the
            // newsfeed had accumulated several rounds of changes
            // (D-154 through D-168) since the account's own cards were
            // first generated. An unconditional full wipe — the same
            // "regenerate everything fresh" approach D-156 already
            // established — is simpler and more thorough than trying
            // to enumerate exactly which rows are stale by which round.
            await db.delete(newsfeedItemTable);
            break;
          case 21:
            // D-170: owner — "I only want #3 and #4. Get rid of both #1
            // and #2" — #1/#2 being streak-milestone and essence-change
            // cards. NewsfeedService no longer generates either type
            // (`_generateStreakItems`/`_generateEssenceItems` deleted
            // outright), but v20's full wipe predates that change, so
            // an account that opened the app between v20 and this
            // migration landing would already have regenerated fresh
            // streak/essence rows. Deletes both types explicitly rather
            // than wiping the whole table again, since sample and
            // article cards (#3/#4) are exactly what the owner wants
            // kept.
            await db.delete(newsfeedItemTable,
                where: '$columnNewsfeedType IN (?, ?)',
                whereArgs: ['streak', 'essence']);
            break;
          case 22:
            // D-178: single account-level personal-info fields, collected
            // during setup (first name) or edited later from the Profile
            // screen (email, phone, a local profile photo path).
            await db.execute(
                'ALTER TABLE $accountStateTable ADD COLUMN $columnFirstName TEXT');
            await db.execute(
                'ALTER TABLE $accountStateTable ADD COLUMN $columnEmail TEXT');
            await db.execute(
                'ALTER TABLE $accountStateTable ADD COLUMN $columnPhone TEXT');
            await db.execute('ALTER TABLE $accountStateTable ADD COLUMN '
                '$columnProfilePhotoPath TEXT');
            break;
        }
      }
    }
    // Always create demo tables if missing
    await db.execute('''
      CREATE TABLE IF NOT EXISTS $demoCategoryTable (
        $columnCategoryId INTEGER PRIMARY KEY,
        $columnCat TEXT NOT NULL,
        UNIQUE($columnCat) ON CONFLICT IGNORE
      )
    ''');
    await db.execute('''
      CREATE TABLE IF NOT EXISTS $demoTaskTable (
        $columnId INTEGER PRIMARY KEY,
        $columnCategory TEXT NOT NULL,
        $columnTaskDescription TEXT NOT NULL,
        $columnSunday TEXT NOT NULL DEFAULT 'true',
        $columnMonday TEXT NOT NULL DEFAULT 'true',
        $columnTuesday TEXT NOT NULL DEFAULT 'true',
        $columnWednesday TEXT NOT NULL DEFAULT 'true',
        $columnThursday TEXT NOT NULL DEFAULT 'true',
        $columnFriday TEXT NOT NULL DEFAULT 'true',
        $columnSaturday TEXT NOT NULL DEFAULT 'true',
        $columnCreateDate TEXT NOT NULL,
        $columnScheduledTime TEXT,
        $columnScheduledCalendarEventId TEXT,
              $columnScheduledDurationMinutes INTEGER,
        UNIQUE($columnCategory, $columnTaskDescription)
      )
    ''');
    await db.execute('''
      CREATE TABLE IF NOT EXISTS $demoTaskLogTable (
        $columnTLId INTEGER PRIMARY KEY,
        $columnTLCategory TEXT NOT NULL,
        $columnTLTaskDescription TEXT NOT NULL,
        $columnTLChecked TEXT NOT NULL,
        $columnTLTaskDate TEXT NOT NULL,
        $columnTLMissReason TEXT,
        UNIQUE($columnTLCategory, $columnTLTaskDescription, $columnTLTaskDate)
      )
    ''');
    await db.execute('''
      CREATE TABLE IF NOT EXISTS $demoQuoteTable (
        $columnQuoteId INTEGER PRIMARY KEY,
        $columnQuoteText TEXT NOT NULL,
        $columnCurrent TEXT NOT NULL
      )
    ''');
    await db.execute('''
      CREATE TABLE IF NOT EXISTS $demoChatTable (
        $chatColumnId INTEGER PRIMARY KEY AUTOINCREMENT,
        $chatColumnSender TEXT NOT NULL,
        $chatColumnContent TEXT NOT NULL,
        $chatColumnTimestamp TEXT NOT NULL
      )
    ''');
  }

// -----------------------------------------------------------------------------
//                                                               populateQuote()
// -----------------------------------------------------------------------------
  void populateQuote() async {
    final List<Map<String, dynamic>> maps = await queryCurrentQuote();
    if (maps.isEmpty) {
      deleteQuote();

      List quoteList = [
        '"Small habits, when done consistently, can lead to extraordinary results." - James Clear',
        '"Focus on the process, not just the outcome. Success is built on the daily actions you take." - James Clear',
        '"You do not rise to the level of your goals; you fall to the level of your systems." - James Clear',
        '"Habits are the compound interest of self-improvement. The effects of your habits multiply as you repeat them." - James Clear',
        '"Make it easy to do the things that are good for you. Design your environment to support your desired habits." - James Clear',
        '"Your habits shape your identity. If you want to change your results, you must first change your identity." - James Clear',
        '"The quality of your life depends on the quality of your habits." - James Clear',
        '"Success is not a one-time event; it is the sum of small actions repeated day in and day out." - James Clear',
        '"Habits are the invisible architecture of everyday life. Make them work for you." - James Clear',
        '"Never underestimate the power of small habits. They have the potential to transform your life." - James Clear',
        '"Your habits shape your identity. Choose them wisely and become the person you aspire to be." - James Clear',
        '"Success is not a singular event but a series of small, daily habits that compound over time." - James Clear',
        '"Habit formation is not about willpower; it is about designing an environment that makes your desired behaviors easier." - James Clear',
        '"The key to lasting change is not setting big, audacious goals, but rather focusing on the small, consistent actions that lead to progress." - James Clear',
        '"Habits are the invisible architecture of our lives. Build them intentionally, and they will shape your destiny." - James Clear',
        '"Mastery is not achieved through occasional bursts of effort, but through the relentless consistency of small habits." - James Clear',
        '"The quality of your life is determined by the quality of your habits. Make them deliberate and watch your life transform." - James Clear',
        '"Success is a product of your habits, not your goals. Focus on building the right habits, and success will follow." - James Clear',
        '"Habits are not a finish line to be crossed but a lifelong journey. Embrace the process and enjoy the progress." - James Clear',
        '"Habits are not a finish line to be crossed but a lifelong journey. Embrace the process and enjoy the progress." - James Clear',
        '"Every action you take is a vote for the type of person you wish to become." - James Clear',
        '"Success is the product of daily habits—not once-in-a-lifetime transformations." - James Clear',
        '"You don'
            't have to be great to start, but you have to start to be great." - James Clear',
        '"Small habits can make a big difference." - James Clear',
        '"Make it easy to do right and hard to go wrong." - James Clear',
        '"The secret to getting results that last is to never stop making improvements." - James Clear',
        '"Master the art of showing up consistently." - James Clear',
        '"It'
            's not about achieving overnight success; it'
            's about making progress consistently." - James Clear',
        '"Make time for the habits that will make you better." - James Clear',
        '"Fall in love with the process of improvement." - James Clear',
        '"You don'
            't need to be the best, you just need to be a little bit better today than you were yesterday." - James Clear',
        '"Focus on progress, not perfection." - James Clear',
        '"The goal is not to get rid of bad habits, but to replace them with good habits." - James Clear',
        '"Habits are the invisible architecture of our lives." - James Clear',
        '"A habit is a behavior that has been repeated enough times to become automatic." - James Clear',
        '"Small changes can have a big impact when they are consistently applied." - James Clear',
        '"The most effective way to change your habits is to focus on your identity." - James Clear',
        '"Your habits shape your identity, and your identity shapes your habits." - James Clear',
        '"Habits are the building blocks of excellence." - James Clear',
        '"The most successful people are the ones with the best habits." - James Clear',
        '"Success is not an event; it' 's a process." - James Clear',
        '"You don'
            't rise to the level of your goals; you fall to the level of your systems." - James Clear',
        '"Habits are like the atoms of our lives. Each one is a fundamental unit that contributes to your overall growth." - James Clear',
        '"Make good habits more convenient and bad habits more difficult." - James Clear',
        '"The path to success is paved with small, consistent actions." - James Clear',
        '"Become 1% better every day." - James Clear',
        '"Tiny changes can lead to remarkable results. Master the art of small habits, and you will unlock extraordinary potential." - James Clear',
        '"Habits are like financial capital – forming one today is an investment that will automatically give out returns for years to come." - Gretchen Rubin',
        '"We are what we repeatedly do. Excellence, then, is not an act but a habit." - Will Durant',
        '"Habit is the intersection of knowledge (what to do), skill (how to do), and desire (want to do)." - Stephen Covey',
        '"The chains of habit are too weak to be felt until they are too strong to be broken." - Samuel Johnson',
        '"Your net worth to the world is usually determined by what remains after your bad habits are subtracted from your good ones." - Benjamin Franklin',
        '"The best way to stop a bad habit is to never begin it." - J.C. Penney',
        '"We first make our habits, and then our habits make us." - John Dryden',
        '"The only way to break a bad habit is to replace it with a good one." - Denis Waitley',
        '"Habit is a cable; we weave a thread each day, and at last, we cannot break it." - Horace Mann',
        '"Lose no time; be always employed in something useful; cut off all unnecessary actions." - Benjamin Franklin',
        '"We cannot solve our problems with the same thinking we used when we created them." - Albert Einstein',
        '"The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking." - Albert Einstein',
        '"Life is like riding a bicycle. To keep your balance, you must keep moving." -  Albert Einstein ',
        '"I write only when inspiration strikes. Fortunately it strikes every morning at nine o'
            'clock sharp." - W. Somerset Maugham',
        '"Hard choices, easy life. Easy choices, hard life." - Jerzy Gregorek'
      ];

      var i = 0;
      quoteList.forEach((quote) async {
        i++;
        // row to insert
        Map<String, dynamic> quoteRow = {
          DatabaseHelper.columnQuoteId: i,
          DatabaseHelper.columnQuoteText: quote,
          DatabaseHelper.columnCurrent: 'N'
        };
        await insertQuote(quoteRow);
      });

      // Choose a single random quote to make current.
      updateRandomCurrentQuote();

      // final List<Map<String, dynamic>> quotes = await queryAllQuotes();
    }
  }

// -----------------------------------------------------------------------------
//                                                          populateTaskLogGap()
// -----------------------------------------------------------------------------

  void populateTaskLogGap() async {
    // for every task in every category, make sure that there is a tasklog
    // entry for the past 7 days for the days of week that are available
    // for that task.

    Database db = await instance.database;

    final intl.DateFormat formatter = intl.DateFormat('yyyy-MM-dd');
    intl.DateFormat dowFmt = intl.DateFormat('EEEE');
    String taskDate;
    String dow;
    // A zero-indexed for loop and increment the days before now().
    for (var i = 0; i <= 6; i++) {
      taskDate = formatter
          .format(DateTime.now().subtract(Duration(days: i)))
          .toString();

      dow =
          dowFmt.format(DateTime.now().subtract(Duration(days: i))).toString();

      // consider the task's day of week blackouts when deciding to
      // insert into tasklog.
      try {
        String query = "insert or ignore into tasklog "
            "(category, taskdescription, checked, taskdate) "
            "select category, taskdescription, 'false', '$taskDate' "
            "from task where $dow = 'true'";
        await db.execute(query);
      } catch (e, s) {
        if (kDebugMode) {
          print(e);
        }
        if (kDebugMode) {
          print(s);
        }
      }
    }
  }

// -----------------------------------------------------------------------------
//                                                            populateCategory()
// -----------------------------------------------------------------------------
  // D-132: was `void populateCategory() async` — nothing could await it, so
  // a caller that genuinely needs all six rows to exist before proceeding
  // (LocalPyramidResetService.wipeLocalPyramid) had no way to wait for
  // them. Existing fire-and-forget callers (main.dart, this class itself)
  // are unaffected — a Future can always be left unawaited.
  Future<void> populateCategory() async {
    await rawInsert("insert into category(categoryid, cat) values"
        "(1, 'Empty1') "
        " on conflict (categoryid) do nothing");

    await rawInsert("insert into category(categoryid, cat) values"
        "(2, 'Empty2') "
        " on conflict (categoryid) do nothing");

    await rawInsert("insert into category(categoryid, cat) values"
        "(3, 'Empty3') "
        " on conflict (categoryid) do nothing");

    await rawInsert("insert into category(categoryid, cat) values"
        "(4, 'Empty4') "
        " on conflict (categoryid) do nothing");

    await rawInsert("insert into category(categoryid, cat) values"
        "(5, 'Empty5') "
        " on conflict (categoryid) do nothing");

    await rawInsert("insert into category(categoryid, cat) values"
        "(6, 'Empty6') "
        " on conflict (categoryid) do nothing");
  }

// Helper methods

  // Inserts a row in the database where each key in the Map is a column name
  // and the value is the column value. The return value is the id of the
  // inserted row.
  Future<int> insertTask(Map<String, dynamic> row) async {
    int id = 0;
    try {
      Database db = await instance.database;
      id = await db.insert(getTaskTable(), row);
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }
    return id;
  }

  // Inserts a row in the database where each key in the Map is a column name
  // and the value is the column value. The return value is the id of the
  // inserted row.
  // D-051/D-084: categoryid is the PRIMARY KEY, and every fresh install
  // already has rows 1-6 seeded by populateCategory() ("Empty1".."Empty6")
  // — the placeholder the pre-Council flow relied on. Without an explicit
  // conflict policy, sqflite's default is ABORT: committing a real derived
  // category for an id that already exists throws, which the catch below
  // swallowed silently in release builds. The real defect this caused: the
  // Council's proposed names never overwrote the seed rows, so setup
  // completed with categories still literally named "Empty1".."Empty6"
  // (found live via Firestore, 2026-09-07) — and the completion screen's
  // pyramid, built from those degenerate rows (every one at position 0),
  // rendered a blank screen instead of failing loudly. REPLACE is what
  // "commit the derived pyramid" always meant here: overwrite whatever
  // was at that id, not refuse to.
  Future<int> insertCategory(Map<String, dynamic> row) async {
    int id = 0;
    try {
      Database db = await instance.database;
      id = await db.insert(getCategoryTable(), row,
          conflictAlgorithm: ConflictAlgorithm.replace);
    } catch (e, s) {
      debugPrint('DatabaseHelper.insertCategory failed for $row: $e\n$s');
    }
    return id;
  }

  // Inserts a row in the database where each key in the Map is a column name
  // and the value is the column value. The return value is the id of the
  // inserted row.
  Future<int> insertTaskLog(Map<String, dynamic> row) async {
    int id = 0;
    try {
      Database db = await instance.database;
      id = await db.insert(getTaskLogTable(), row);
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }
    return id;
  }

  // All of the rows are returned as a list of maps, where each map is
  // a key-value list of columns.
  Future<List<Map<String, dynamic>>> query() async {
    late List<Map<String, dynamic>> ret;
    try {
      Database db = await instance.database;
      ret = await db.query(getTaskTable());
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }
    return ret;
  }

  // return -1 if there are no tasks at all for this category.
  Future<int> getCompletionPercentage(String cat, int days) async {
    Database db = await instance.database;
    // First, check if there are any tasks for this category
    final taskTable = getTaskTable();
    final taskRes = await db
        .query(taskTable, where: '$columnCategory = ?', whereArgs: [cat]);
    if (taskRes.isEmpty) {
      return -1; // No tasks defined for this category
    }
    final intl.DateFormat formatter = intl.DateFormat('yyyy-MM-dd');
    var fromDate = formatter
        .format(DateTime.now().subtract(Duration(days: days)))
        .toString();
    final table = getTaskLogTable();
    print('[RADAR][PCT] Using table: $table for category: $cat');
    var q1 = "select * from $table where category = ? and taskdate >= ?";
    final res1 = await db.rawQuery(q1, [cat, fromDate]);
    var total = res1.length;
    print('[RADAR][PCT] Total logs for $cat: $total');
    var q2 =
        "select * from $table where category = ? and taskdate >= ? and checked = 'true'";
    final res2 = await db.rawQuery(q2, [cat, fromDate]);
    var checked = res2.length;
    print('[RADAR][PCT] Checked logs for $cat: $checked');
    if (total == 0) {
      return 0; // Tasks exist, but no logs in range
    }
    var percentage = ((checked / total) * 100).toInt();
    print('[RADAR][PCT] Percentage for $cat: $percentage');
    return percentage;
  }

  // return '' if there are no tasks at all.
  Future<String> getTotalPercentage(int days) async {
    await instance.database;
    // Get all categories (1-6)
    List<String> cats = [];
    try {
      final catMaps = await queryCategories();
      for (var i = 1; i <= 6; i++) {
        final match = catMaps.firstWhere(
          (c) => c['categoryid'] == i,
          orElse: () => <String, dynamic>{},
        );
        if (match.isNotEmpty && match['cat'] != null) cats.add(match['cat']);
      }
    } catch (e) {
      print('[TOTAL PCT] Error loading categories: $e');
    }
    if (cats.isEmpty) return '0';
    int sum = 0;
    int count = 0;
    for (final cat in cats) {
      final pct = await getCompletionPercentage(cat, days);
      if (pct >= 0) {
        sum += pct;
        count++;
      }
    }
    if (count == 0) return '0';
    final avg = (sum / count).round();
    print('[TOTAL PCT] Per-category: $cats, avg: $avg');
    return avg.toString();
  }

  Future<List<Map<String, dynamic>>> queryUncheckedTasks(String logDate) async {
    late List<Map<String, dynamic>> ret;
    try {
      Database db = await instance.database;
      List<dynamic> whereArguments = [logDate];
      ret = await db.query(getTaskLogTable(),
          where: "checked = 'false' and ${DatabaseHelper.columnTLTaskDate} = ?",
          whereArgs: whereArguments);
    } catch (e, s) {
      print(e);
      print(s);
    }
    return ret;
  }

  Future<List<Map<String, dynamic>>> queryCheckedTasks(String logDate) async {
    late List<Map<String, dynamic>> ret;
    try {
      Database db = await instance.database;
      List<dynamic> whereArguments = [logDate];
      ret = await db.query(getTaskLogTable(),
          where: "checked = 'true' and ${DatabaseHelper.columnTLTaskDate} = ?",
          whereArgs: whereArguments);
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      print(s);
    }
    return ret;
  }

  Future<List<Map<String, dynamic>>> queryCategories() async {
    late List<Map<String, dynamic>> ret;
    try {
      Database db = await instance.database;
      ret = await db.query(getCategoryTable());
    } catch (e, s) {
      print(e);
      print(s);
    }
    return ret;
  }

  Future<List<Map<String, dynamic>>> queryCategory(int categoryid) async {
    late List<Map<String, dynamic>> ret;
    try {
      Database db = await instance.database;
      List<dynamic> whereArguments = [categoryid];
      ret = await db.query(getCategoryTable(),
          where: "${DatabaseHelper.columnCategoryId} = ?",
          whereArgs: whereArguments);
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      print(s);
    }
    return ret;
  }

  Future<List<Map<String, dynamic>>> queryCurrentQuote() async {
    late List<Map<String, dynamic>> ret;
    try {
      Database db = await instance.database;
      ret = await db.query(getQuoteTable(), where: "current = 'Y'");
    } catch (e, s) {
      print(e);
      print(s);
    }
    return ret;
  }

  Future<List<Map<String, dynamic>>> queryAllQuotes() async {
    late List<Map<String, dynamic>> ret;
    try {
      Database db = await instance.database;
      ret = await db.query(getQuoteTable());
    } catch (e, s) {
      print(e);
      print(s);
    }
    return ret;
  }

  Future<List<Map<String, dynamic>>> queryTaskLogByCategory(
      String cat, String logDate) async {
    late List<Map<String, dynamic>> ret;
    try {
      Database db = await instance.database;
      List<dynamic> whereArguments = [cat, logDate];
      ret = await db.query(getTaskLogTable(),
          where:
              '${DatabaseHelper.columnCategory} = ? and ${DatabaseHelper.columnTLTaskDate} = ?',
          whereArgs: whereArguments);
    } catch (e, s) {
      print(e);
      print(s);
    }
    return ret;
  }

  Future<List<Map<String, dynamic>>> queryAllTasks() async {
    late List<Map<String, dynamic>> ret;
    try {
      Database db = await instance.database;
      ret = await db.query(getTaskTable());
    } catch (e, s) {
      print(e);
      print(s);
    }
    return ret;
  }

  Future<List<Map<String, dynamic>>> queryTaskLogs(int days) async {
    late List<Map<String, dynamic>> ret;

    final intl.DateFormat formatter = intl.DateFormat('yyyy-MM-dd');

    var fromDate = formatter
        .format(DateTime.now().subtract(Duration(days: days)))
        .toString();

    var toDate = formatter.format(DateTime.now()).toString();

    try {
      Database db = await instance.database;

      var query = "select * from ${getTaskLogTable()} where "
          "taskdate >= '$fromDate' and "
          "taskdate < '$toDate'"
          "order by taskdate";
      ret = await db.rawQuery(query);
    } catch (e, s) {
      print(e);
      print(s);
    }
    return ret;
  }

  /// D-171: every task_log row, full stop — the sync source for
  /// `recentActivity`, so a full uninstall/reinstall can restore every
  /// check-off ever recorded, not just a recent window (D-075's original
  /// 250-row bound is gone; see D-171).
  Future<List<Map<String, dynamic>>> queryAllTaskLogs() async {
    late List<Map<String, dynamic>> ret;
    try {
      Database db = await instance.database;
      ret = await db.query(getTaskLogTable());
    } catch (e, s) {
      print(e);
      print(s);
    }
    return ret;
  }

  Future<List<Map<String, dynamic>>> queryForProfile() async {
    late List<Map<String, dynamic>> ret;

    try {
      Database db = await instance.database;

      var query = "select distinct category, taskdescription  "
          "from tasklog";
      ret = await db.rawQuery(query);
    } catch (e, s) {
      print(e);
      print(s);
    }
    return ret;
  }

  Future<int> queryLaunchSetup() async {
    late List<Map<String, dynamic>> maps;

    try {
      Database db = await instance.database;

      var query = "select count(*) as defaults from category where "
          "cat like 'Empty%'";
      maps = await db.rawQuery(query);
    } catch (e, s) {
      print(e);
      if (kDebugMode) {
        print(s);
      }
    }

    return await maps[0]['defaults'];
  }

  Future<List<Map<String, dynamic>>> queryTasksByCategory(String cat) async {
    late List<Map<String, dynamic>> ret;
    try {
      Database db = await instance.database;
      List<dynamic> whereArguments = [cat];
      ret = await db.query(getTaskTable(),
          where: '${DatabaseHelper.columnCategory} = ?',
          whereArgs: whereArguments);
    } catch (e, s) {
      print(e);
      print(s);
    }
    return ret;
  }

  Future<List<Map<String, dynamic>>> querySingleTask(
      String cat, String desc) async {
    late List<Map<String, dynamic>> ret;
    try {
      Database db = await instance.database;
      List<dynamic> whereArguments = [cat, desc];
      ret = await db.query(getTaskTable(),
          where:
              '${DatabaseHelper.columnCategory} = ? and ${DatabaseHelper.columnTaskDescription} = ?',
          whereArgs: whereArguments);
    } catch (e, s) {
      print(e);
      print(s);
    }
    return ret;
  }

  insertTaskLogForCategory(String cat, String logDate, String dow) async {
    Database db = await instance.database;

    // consider the task's day of week blackouts when deciding to
    // insert into tasklog.
    try {
      String query = "insert into tasklog "
          "(category, taskdescription, checked, taskdate) "
          "select category, taskdescription, 'false', '$logDate' "
          "from task where category = '$cat' and $dow = 'true'";
      await db.execute(query);
    } catch (e, s) {
      print(e);
      print(s);
    }
  }

  Future<int> insertQuote(Map<String, dynamic> row) async {
    int id = 0;
    try {
      Database db = await instance.database;
      id = await db.insert(getQuoteTable(), row);
    } catch (e, s) {
      print(e);
      print(s);
    }
    return id;
  }

  Future<int> updateRandomCurrentQuote() async {
    // update all rows to current = 'N';
    await _database
        .rawUpdate("update quote set current = 'N' where current = 'Y'");

    // grab a random row id.
    var q1 = 'select quoteid from quote order by random() limit 1';
    var rs = await _database.rawQuery(q1);
    var randomRow = rs.first;
    var currentQuoteId = randomRow['quoteid'];

    // set the random row to current.
    await _database.rawUpdate(
        "update quote set current = 'Y' where quoteid = $currentQuoteId");

    final List<Map<String, dynamic>> maps = await queryCurrentQuote();

    return await maps[0]['quoteid'];
  }

  // We are assuming here that the id column in the map is set. The other
  // column values will be used to update the row.
  Future<int> update(Map<String, dynamic> row) async {
    Database db = await instance.database;
    int id = row[columnId];
    return await db
        .update(getTaskTable(), row, where: '$columnId = ?', whereArgs: [id]);
  }

  // update review
  Future<int> updateReview(String upd) async {
    Database db = await instance.database;
    return await db.rawUpdate(upd);
  }

  /// Sets one day-of-week flag on a task. Parameterized: [day] is validated
  /// against a fixed allowlist so it can never carry injected SQL, and the
  /// user-entered category and description are bound, never interpolated.
  ///
  /// D-024: extracted from lib/screens/edittaskdetail.dart, which built this
  /// statement by string interpolation of user input.
  static const Set<String> dayColumns = {
    'sunday',
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday',
    'saturday'
  };

  Future<int> setTaskDayFlag({
    required String category,
    required String taskDescription,
    required String day,
    required bool value,
  }) async {
    if (!dayColumns.contains(day)) {
      throw ArgumentError.value(day, 'day', 'not a day-of-week column');
    }
    final db = await instance.database;
    return db.update(
      getTaskTable(),
      {day: value.toString()},
      where: '$columnCategory = ? AND $columnTaskDescription = ?',
      whereArgs: [category, taskDescription],
    );
  }

  /// Renames a task within a category. Parameterized.
  ///
  /// D-024: extracted from lib/screens/edittaskdetail.dart.
  Future<int> renameTask({
    required String category,
    required String oldDescription,
    required String newDescription,
  }) async {
    final db = await instance.database;
    return db.update(
      getTaskTable(),
      {columnTaskDescription: newDescription},
      where: '$columnCategory = ? AND $columnTaskDescription = ?',
      whereArgs: [category, oldDescription],
    );
  }

  /// Creates or renames a category at a fixed pyramid slot. Parameterized.
  ///
  /// D-024: extracted from lib/screens/editpyramid.dart, which interpolated
  /// the user-entered name straight into SQL.
  ///
  /// D-084 will extend this to cascade the rename into `task` and `task_log`,
  /// which key on the category *name*. Until then, renaming still orphans a
  /// category's habits — see II-N.
  Future<int> upsertCategoryAt(int categoryid, String cat) async {
    final db = await instance.database;
    return db.rawInsert(
      'INSERT INTO ${getCategoryTable()} ($columnCategoryId, $columnCat) '
      'VALUES (?, ?) '
      'ON CONFLICT ($columnCategoryId) DO UPDATE SET $columnCat = ?',
      [categoryid, cat, cat],
    );
  }

  /// Inserts or updates a task at an explicit id. Parameterized.
  ///
  /// D-024: extracted from lib/screens/setup/setup18.dart, which built this
  /// statement by interpolating model-generated text into SQL and stripped
  /// apostrophes to stop it breaking the query. Binding the arguments removes
  /// both the injection path and the need to mangle the text.
  Future<int> upsertTaskAt({
    required int id,
    required String category,
    required String taskDescription,
    required String sunday,
    required String monday,
    required String tuesday,
    required String wednesday,
    required String thursday,
    required String friday,
    required String saturday,
    required String createDate,
  }) async {
    final db = await instance.database;
    return db.insert(
      getTaskTable(),
      {
        columnId: id,
        columnCategory: category,
        columnTaskDescription: taskDescription,
        columnSunday: sunday,
        columnMonday: monday,
        columnTuesday: tuesday,
        columnWednesday: wednesday,
        columnThursday: thursday,
        columnFriday: friday,
        columnSaturday: saturday,
        columnCreateDate: createDate,
      },
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
  }

  /// Renames a category and cascades the new name into `task` and `tasklog`.
  ///
  /// D-084. `task` and `tasklog` key on the category *name*, so renaming
  /// without cascading orphans every habit and log row under that category —
  /// the shipped defect recorded in II-N. All three writes happen in one
  /// transaction: either the rename lands everywhere or nowhere.
  ///
  /// Tables added by R3 key on `categoryid` and need no update here.
  Future<void> renameCategoryCascading({
    required int categoryid,
    required String newName,
  }) async {
    final db = await instance.database;
    await db.transaction((txn) async {
      final existing = await txn.query(
        getCategoryTable(),
        columns: [columnCat],
        where: '$columnCategoryId = ?',
        whereArgs: [categoryid],
      );
      final oldName =
          existing.isEmpty ? null : existing.first[columnCat] as String?;

      await txn.rawInsert(
        'INSERT INTO ${getCategoryTable()} ($columnCategoryId, $columnCat) '
        'VALUES (?, ?) '
        'ON CONFLICT ($columnCategoryId) DO UPDATE SET $columnCat = ?',
        [categoryid, newName, newName],
      );

      if (oldName == null || oldName == newName) return;

      await txn.update(getTaskTable(), {columnCategory: newName},
          where: '$columnCategory = ?', whereArgs: [oldName]);
      await txn.update(getTaskLogTable(), {columnTLCategory: newName},
          where: '$columnTLCategory = ?', whereArgs: [oldName]);
    });
  }

  /// Marks a habit checked or unchecked for a given date. Parameterized.
  ///
  /// D-024: extracted from lib/screens/tasklist.dart. This is the core daily
  /// interaction and was previously built by interpolating user-entered text
  /// into a SQL string.
  Future<int> setTaskLogChecked({
    required String category,
    required String taskDescription,
    required String taskDate,
    required bool checked,
  }) async {
    final db = await instance.database;
    return db.update(
      getTaskLogTable(),
      {columnTLChecked: checked.toString()},
      where: '$columnTLCategory = ? AND $columnTLTaskDescription = ? '
          'AND $columnTLTaskDate = ?',
      whereArgs: [category, taskDescription, taskDate],
    );
  }

  /// D-124: records one habit's answer from the batch check-in screen —
  /// Yes (`checked: true`, no reason) or No (`checked: false`, an
  /// optional voice-transcribed reason). Ensures a tasklog row exists for
  /// [taskDate] first (mirroring [insertTaskLogForCategory]'s own
  /// insert-if-missing pattern via the UNIQUE constraint), since the push
  /// that led here may have arrived on a device that never opened the
  /// task list today and so never auto-created one.
  Future<void> recordBatchCheckinResult({
    required String category,
    required String taskDescription,
    required String taskDate,
    required bool checked,
    String? missReason,
  }) async {
    final db = await instance.database;
    try {
      await db.insert(getTaskLogTable(), {
        columnTLCategory: category,
        columnTLTaskDescription: taskDescription,
        columnTLChecked: 'false',
        columnTLTaskDate: taskDate,
      });
    } catch (_) {
      // A row for today already exists — the update below is what matters.
    }
    await db.update(
      getTaskLogTable(),
      {
        columnTLChecked: checked.toString(),
        columnTLMissReason: missReason,
      },
      where: '$columnTLCategory = ? AND $columnTLTaskDescription = ? '
          'AND $columnTLTaskDate = ?',
      whereArgs: [category, taskDescription, taskDate],
    );
  }

  /// Deletes every log row for one habit. Parameterized.
  ///
  /// D-024: extracted from lib/screens/edittaskdetail.dart.
  Future<int> deleteTaskLogsForTask({
    required String category,
    required String taskDescription,
  }) async {
    final db = await instance.database;
    return db.delete(
      getTaskLogTable(),
      where: '$columnTLCategory = ? AND $columnTLTaskDescription = ?',
      whereArgs: [category, taskDescription],
    );
  }

  /// Deletes every task and log row belonging to a category. Parameterized.
  ///
  /// D-024: extracted from lib/screens/editpyramid.dart.
  Future<void> deleteCategoryContents(String category) async {
    final db = await instance.database;
    await db.delete(getTaskLogTable(),
        where: '$columnTLCategory = ?', whereArgs: [category]);
    await db.delete(getTaskTable(),
        where: '$columnCategory = ?', whereArgs: [category]);
  }

  Future<int> rawUpdate(String upd) async {
    Database db = await instance.database;
    return await db.rawUpdate(upd);
  }

  Future<int> rawInsert(String ins) async {
    Database db = await instance.database;
    return await db.rawInsert(ins);
  }

  Future<int> rawDelete(String del) async {
    Database db = await instance.database;
    return await db.rawDelete(del);
  }

  Future<List<Map>> rawQuery(String qry) async {
    Database db = await instance.database;
    return await db.rawQuery(qry);
  }

  // Deletes the row specified by the id. The number of affected rows is
  // returned. This should be 1 as long as the row exists.
  Future<int> delete(int id) async {
    Database db = await instance.database;
    return await db
        .delete(getTaskTable(), where: '$columnId = ?', whereArgs: [id]);
  }

  // Deletes a task and every task-log entry it produced — including the
  // current day's already-generated entry — in a single transaction, scoped
  // to [category] so an identically named task in another category is left
  // untouched. Previously only the task row was removed, so today's log
  // entry survived and the deleted task kept appearing in the day's Log
  // (it can't regenerate once the task row is gone, since the day's log is
  // rebuilt from the task table).
  Future<void> deleteTaskAndLog(String category, String taskDescription) async {
    Database db = await instance.database;
    await db.transaction((txn) async {
      await txn.delete(getTaskTable(),
          where: '$columnCategory = ? and $columnTaskDescription = ?',
          whereArgs: [category, taskDescription]);
      await txn.delete(getTaskLogTable(),
          where: '$columnTLCategory = ? and $columnTLTaskDescription = ?',
          whereArgs: [category, taskDescription]);
    });
  }

  Future<int> deleteTasks() async {
    Database db = await instance.database;
    return await db.delete(getTaskTable());
  }

  Future<int> deleteTaskLog() async {
    Database db = await instance.database;
    return await db.delete(getTaskLogTable());
  }

  Future<int> deleteQuote() async {
    Database db = await instance.database;
    return await db.delete(getQuoteTable());
  }

  Future<int> deleteCategory() async {
    Database db = await instance.database;
    return await db.delete(getCategoryTable());
  }

  Future<int> insertVisionStatement(String visionText) async {
    int id = 0;
    try {
      Database db = await instance.database;
      id = await db.insert(visionStatementTable, {
        columnVisionText: visionText,
        columnVisionCreated: DateTime.now().toIso8601String(),
      });
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }
    return id;
  }

  Future<String?> getLatestVisionStatement() async {
    try {
      Database db = await instance.database;
      final result = await db.query(
        visionStatementTable,
        orderBy: '$columnVisionCreated DESC',
        limit: 1,
      );
      if (result.isNotEmpty) {
        return result.first[columnVisionText] as String;
      }
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }
    return null;
  }

  // --- R4 / Part IV: account_state, and reads that feed SyncService ------

  /// The single account_state row (D-030). The row always exists after
  /// applyV7Schema's `INSERT OR IGNORE`, so this never returns null.
  Future<Map<String, dynamic>> getAccountState() async {
    final db = await database;
    final rows = await db.query(accountStateTable,
        where: '$columnAccountId = ?', whereArgs: [1]);
    return rows.first;
  }

  /// D-032/D-034: records the Firebase uid once anonymous sign-in succeeds.
  Future<void> setAccountUid(String uid) async {
    final db = await database;
    await db.update(
        accountStateTable,
        {
          columnAccountUid: uid,
          columnEntitlementSyncedAt: DateTime.now().toIso8601String(),
        },
        where: '$columnAccountId = ?',
        whereArgs: [1]);
  }

  Future<void> setAccountTimezone(String timezone) async {
    final db = await database;
    await db.update(accountStateTable, {columnAccountTimezone: timezone},
        where: '$columnAccountId = ?', whereArgs: [1]);
  }

  /// D-178: collected once during setup (a plain text-entry screen right
  /// before the pyramid is built), editable afterward from the Profile
  /// screen. Used throughout the app — AI prompts included — instead of
  /// generic "you"/"this person" phrasing.
  Future<void> setFirstName(String firstName) async {
    final db = await database;
    await db.update(accountStateTable, {columnFirstName: firstName},
        where: '$columnAccountId = ?', whereArgs: [1]);
  }

  /// D-178: pure personal-reference fields from the Profile screen — no
  /// functional behavior (not used for verification, recovery, or
  /// notifications), so a blank string clears a field rather than being
  /// rejected.
  Future<void> setEmail(String email) async {
    final db = await database;
    await db.update(accountStateTable, {columnEmail: email},
        where: '$columnAccountId = ?', whereArgs: [1]);
  }

  Future<void> setPhone(String phone) async {
    final db = await database;
    await db.update(accountStateTable, {columnPhone: phone},
        where: '$columnAccountId = ?', whereArgs: [1]);
  }

  /// D-178: local file path only — the photo itself stays on-device, not
  /// synced to Firestore (owner's own choice: cloud photo storage would
  /// mean adding Firebase Storage, a new integration not approved yet).
  Future<void> setProfilePhotoPath(String? path) async {
    final db = await database;
    await db.update(accountStateTable, {columnProfilePhotoPath: path},
        where: '$columnAccountId = ?', whereArgs: [1]);
  }

  /// D-057: writes the server-authoritative entitlement into the local
  /// cache. Called only by EntitlementService, after a real server response
  /// (a /requestTrial reply or a profile/main pull) — never from anything
  /// derived purely on-device, since this row "can report a trial, never
  /// extend one."
  Future<void> setAccountEntitlement({
    required String entitlement,
    String? trialStartedAt,
    String? trialExpiresAt,
  }) async {
    final db = await database;
    await db.update(
        accountStateTable,
        {
          columnEntitlement: entitlement,
          columnTrialStartedAt: trialStartedAt,
          columnTrialExpiresAt: trialExpiresAt,
          columnEntitlementSyncedAt: DateTime.now().toIso8601String(),
        },
        where: '$columnAccountId = ?',
        whereArgs: [1]);
  }

  /// D-075: every version of every category's essence — part of the synced
  /// set.
  Future<List<Map<String, dynamic>>> queryAllCategoryEssences() async {
    final db = await database;
    return db.query(categoryEssenceTable);
  }

  /// D-047: resolves a category's id from its name — the category detail
  /// screen is addressed by name, but essence lookup keys on id (D-084).
  /// Null if no category with this name exists.
  Future<int?> getCategoryIdByName(String cat) async {
    final db = await database;
    final rows = await db.query(getCategoryTable(),
        where: '$columnCat = ?', whereArgs: [cat], limit: 1);
    if (rows.isEmpty) return null;
    return rows.first[columnCategoryId] as int?;
  }

  /// D-028/D-061: the active (most recent) essence for one category, the
  /// context a Council re-clarification session opens with. Null if the
  /// category has never had an essence captured — a first-class state
  /// (D-005), not an error.
  Future<String?> getLatestEssenceForCategory(int categoryId) async {
    final db = await database;
    final rows = await db.query(categoryEssenceTable,
        where: '$columnEssenceCategoryId = ?',
        whereArgs: [categoryId],
        orderBy: '$columnEssenceCreated DESC',
        limit: 1);
    if (rows.isEmpty) return null;
    return rows.first[columnEssenceText] as String?;
  }

  /// D-095: id, name, tier, and latest essence for every category — the
  /// shape the general Council conversation (D-091) needs to ground its
  /// advice in the user's actual pyramid, not a placeholder. Tier follows
  /// the same position convention used throughout setup (1-3 foundational,
  /// 4-5 essential, 6 peak). Reuses [getLatestEssenceForCategory] per
  /// category rather than re-deriving "latest essence" with a second
  /// reduction over every essence row (SyncService._syncProfile already
  /// has one; this isn't a third). D-100: `id` (added after the pyramid-
  /// grounding shape first shipped) is how a general Council domain
  /// finding, named by the model against `name`, resolves back to a real
  /// `categoryId` for `insertDomainFinding` — never sent over the wire
  /// itself, only used locally.
  Future<List<Map<String, dynamic>>> queryPyramidSummary() async {
    final rows = await queryCategories();
    // db.query()'s result is sqflite's own read-only list — sort a copy,
    // never the original (the exact defect query_categories_readonly_test
    // covers elsewhere).
    final sorted = List<Map<String, dynamic>>.from(rows)
      ..sort((a, b) =>
          (a[columnPosition] as int).compareTo(b[columnPosition] as int));

    final summary = <Map<String, dynamic>>[];
    for (final row in sorted) {
      final id = row[columnCategoryId] as int;
      final position = row[columnPosition] as int;
      final tier =
          position <= 3 ? 'foundational' : (position <= 5 ? 'essential' : 'peak');
      summary.add({
        'id': id,
        'name': row[columnCat] as String,
        'tier': tier,
        'essence': await getLatestEssenceForCategory(id),
      });
    }
    return summary;
  }

  /// D-150: the longest run of consecutive days, ending on the most recent
  /// day with any tasklog activity for this category, where at least one
  /// of that day's tasks was checked. Same "group by date, walk sorted
  /// dates" approach visualizations.dart's _loadStreaksData already uses
  /// for its longest-ever streak — this instead only cares about the
  /// *current, still-active* run, which is what a "you're on a streak"
  /// newsfeed item needs (an ended streak isn't news).
  Future<int> getCurrentStreak(String categoryName) async {
    final db = await database;
    final rows = await db.query(getTaskLogTable(),
        where: '$columnTLCategory = ?', whereArgs: [categoryName]);
    final Map<String, bool> dailyCompletion = {};
    for (final row in rows) {
      final date = row[columnTLTaskDate] as String;
      dailyCompletion[date] =
          (dailyCompletion[date] ?? false) || row[columnTLChecked] == 'true';
    }
    final sortedDates = dailyCompletion.keys.toList()..sort();
    int streak = 0;
    for (final date in sortedDates.reversed) {
      if (dailyCompletion[date] != true) break;
      streak++;
    }
    return streak;
  }

  /// D-150: writes one newsfeed item, silently skipped (INSERT OR IGNORE)
  /// if [dedupeKey] was already used — the mechanism that makes calling
  /// the generator repeatedly (every time the newsfeed screen opens) safe.
  /// D-154: now returns whether the row was actually inserted (`true`) or
  /// silently ignored as a duplicate (`false`) — sqflite's `insert()`
  /// returns `0` on an ignored conflict (confirmed against the real
  /// sqflite package, not assumed), which is what a caller needs to know
  /// whether this is a genuinely *new* item worth firing a local
  /// notification for.
  /// D-158: [createdAt] lets a caller place an item at a deliberate
  /// position in the feed's newest-first order rather than always "now"
  /// — the seeded welcome cards use this to stay apart from each other
  /// (see NewsfeedService._seedWelcomeCards).
  Future<bool> insertNewsfeedItem({
    required String type,
    required String title,
    required String body,
    int? categoryId,
    required String dedupeKey,
    DateTime? createdAt,
  }) async {
    final db = await database;
    final id = await db.insert(
      newsfeedItemTable,
      {
        columnNewsfeedType: type,
        columnNewsfeedTitle: title,
        columnNewsfeedBody: body,
        columnNewsfeedCategoryId: categoryId,
        columnNewsfeedCreated: (createdAt ?? DateTime.now()).toIso8601String(),
        columnNewsfeedDedupeKey: dedupeKey,
      },
      conflictAlgorithm: ConflictAlgorithm.ignore,
    );
    return id != 0;
  }

  /// D-150: one page of the newsfeed, newest first.
  Future<List<Map<String, dynamic>>> queryNewsfeedItems({
    required int limit,
    required int offset,
  }) async {
    final db = await database;
    return db.query(
      newsfeedItemTable,
      orderBy: '$columnNewsfeedCreated DESC, $columnNewsfeedId DESC',
      limit: limit,
      offset: offset,
    );
  }

  /// D-155: a cheap existence check by dedupeKey, used before doing any
  /// of the (comparatively expensive) per-category stat-gathering or the
  /// AI call itself for the newsfeed's daily article — so a day that
  /// already has its article never re-does that work just to have
  /// insertNewsfeedItem's own dedup silently discard the result at the
  /// very end.
  Future<bool> newsfeedItemExists(String dedupeKey) async {
    final db = await database;
    final rows = await db.query(newsfeedItemTable,
        where: '$columnNewsfeedDedupeKey = ?', whereArgs: [dedupeKey], limit: 1);
    return rows.isNotEmpty;
  }

  /// D-168: how many on-demand articles have already been generated
  /// today — [prefix] is the day's own `article-<date>-manual-` stem, so
  /// this only ever counts today's on-demand generations, never the
  /// automatic daily one (a different dedupeKey shape entirely) or a
  /// prior day's. Used to enforce the daily on-demand cap before doing
  /// any stat-gathering or AI call.
  Future<int> countNewsfeedItemsWithDedupeKeyPrefix(String prefix) async {
    final db = await database;
    final result = await db.rawQuery(
        'SELECT COUNT(*) FROM $newsfeedItemTable WHERE $columnNewsfeedDedupeKey LIKE ?',
        ['$prefix%']);
    return Sqflite.firstIntValue(result) ?? 0;
  }


  /// D-154: the 0-based rank of the item identified by [dedupeKey] within
  /// the same newest-first ordering [queryNewsfeedItems] pages through —
  /// how a notification tap can jump the newsfeed screen straight to a
  /// specific item (load pages up to and including this rank, then
  /// scroll to it) without paging through the entire history first.
  /// Returns null if no such item exists (e.g., its dedupeKey is stale).
  Future<int?> getNewsfeedItemPosition(String dedupeKey) async {
    final db = await database;
    final rows = await db.query(newsfeedItemTable,
        where: '$columnNewsfeedDedupeKey = ?', whereArgs: [dedupeKey], limit: 1);
    if (rows.isEmpty) return null;
    final target = rows.first;
    final targetCreated = target[columnNewsfeedCreated] as String;
    final targetId = target[columnNewsfeedId] as int;
    final result = await db.rawQuery(
        'SELECT COUNT(*) AS c FROM $newsfeedItemTable WHERE '
        '$columnNewsfeedCreated > ? OR ($columnNewsfeedCreated = ? AND $columnNewsfeedId > ?)',
        [targetCreated, targetCreated, targetId]);
    return Sqflite.firstIntValue(result) ?? 0;
  }

  /// D-028/D-061: appends a new essence version for a category (essences are
  /// versioned, never overwritten — D-061). D-166: a no-op — returns
  /// `false`, inserts nothing — when [essence] is identical to the
  /// category's current latest version. Found live: `SyncService
  /// .restoreFromCloud` called this unconditionally on every restore,
  /// manufacturing a brand-new "version" with the exact same text as
  /// before purely as a side effect of syncing — seven or more phantom
  /// "redefinitions" per category on one real account, none of them an
  /// actual change the user made. Guarding here, in the shared insert
  /// path, protects every caller uniformly (not just restoreFromCloud) —
  /// a version-history table recording the same value twice in a row is
  /// never meaningful, regardless of which caller triggered it. Returns
  /// `true` iff a new row was actually inserted, so a caller (the
  /// newsfeed's own notification path, for one) can tell whether a real
  /// change happened.
  Future<bool> insertCategoryEssence({
    required int categoryId,
    required String essence,
    String? sourceSessionId,
  }) async {
    final current = await getLatestEssenceForCategory(categoryId);
    if (current == essence) return false;
    final db = await database;
    await db.insert(categoryEssenceTable, {
      columnEssenceCategoryId: categoryId,
      columnEssenceText: essence,
      columnEssenceCreated: DateTime.now().toIso8601String(),
      columnEssenceSourceSession: sourceSessionId,
    });
    return true;
  }

  /// D-048: records one domain finding surfaced during a category
  /// conversation. Findings accumulate — never overwritten, never
  /// deduplicated — since the same impediment resurfacing over time is
  /// itself part of the record (P-16).
  Future<void> insertDomainFinding({
    required int categoryId,
    required String domain,
    required String note,
    String? sourceSessionId,
  }) async {
    final db = await database;
    await db.insert(domainFindingTable, {
      columnFindingCategoryId: categoryId,
      columnFindingDomain: domain,
      columnFindingNote: note,
      columnFindingCreated: DateTime.now().toIso8601String(),
      columnFindingSourceSession: sourceSessionId,
    });
  }

  /// D-075: accumulated four-domain findings — part of the synced set.
  Future<List<Map<String, dynamic>>> queryAllDomainFindings() async {
    final db = await database;
    return db.query(domainFindingTable);
  }

  /// D-049: findings grouped by domain, for the domain-map view. Domain
  /// state is derived from accumulated findings, never asked of the user
  /// directly (D-049's own acceptance criterion).
  Future<Map<String, List<Map<String, dynamic>>>>
      queryDomainFindingsByDomain() async {
    final rows = await queryAllDomainFindings();
    final byDomain = <String, List<Map<String, dynamic>>>{};
    for (final row in rows) {
      final domain = row[columnFindingDomain] as String;
      (byDomain[domain] ??= []).add(row);
    }
    return byDomain;
  }


  Future<void> insertChatMessage(String sender, String content) async {
    final db = await database;
    await db.insert(getChatTable(), {
      chatColumnSender: sender,
      chatColumnContent: content,
      chatColumnTimestamp: DateTime.now().toIso8601String(),
    });
  }

  Future<List<Map<String, dynamic>>> getChatHistory() async {
    final db = await database;
    return await db.query(getChatTable(), orderBy: '$chatColumnTimestamp ASC');
  }

  Future<void> deleteOldestChatMessage(int messageId) async {
    final db = await database;
    await db.delete(getChatTable(),
        where: '$chatColumnId = ?', whereArgs: [messageId]);
  }

  // Commentary countdown methods
  Future<void> saveCommentaryCountdown(int countdown) async {
    try {
      Database db = await instance.database;
      // Delete existing countdown
      await db.delete(commentaryCountdownTable);
      // Insert new countdown
      await db.insert(commentaryCountdownTable, {
        columnCountdownId: 1,
        columnCountdownValue: countdown,
      });
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }
  }

  Future<int> getCommentaryCountdown() async {
    try {
      Database db = await instance.database;
      final result = await db.query(
        commentaryCountdownTable,
        where: '$columnCountdownId = ?',
        whereArgs: [1],
      );
      if (result.isNotEmpty) {
        return result.first[columnCountdownValue] as int;
      }
    } catch (e, s) {
      if (kDebugMode) {
        print(e);
      }
      if (kDebugMode) {
        print(s);
      }
    }
    return 30; // Default value if not found
  }
}

class Task {
  int id = 0;
  String category = '';
  String taskdescription = '';
  String sunday = '';
  String monday = '';
  String tuesday = '';
  String wednesday = '';
  String thursday = '';
  String friday = '';
  String saturday = '';

  Task(
      {required this.id,
      required this.category,
      required this.taskdescription,
      required this.sunday,
      required this.monday,
      required this.tuesday,
      required this.wednesday,
      required this.thursday,
      required this.friday,
      required this.saturday});

  Task.fromMap(dynamic obj) {
    id = obj["id"];
    category = obj["category"];
    taskdescription = obj["taskdescription"];
    sunday = obj["sunday"];
    monday = obj["monday"];
    tuesday = obj["tuesday"];
    wednesday = obj["wednesday"];
    thursday = obj["thursday"];
    friday = obj["friday"];
    saturday = obj["saturday"];
  }
}

class ChatMessage {
  final int? id;
  final String role; // 'user' or 'assistant'
  final String content;

  ChatMessage({this.id, required this.role, required this.content});

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'sender': role,
      'content': content,
    };
  }

  static ChatMessage fromMap(Map<String, dynamic> map) {
    return ChatMessage(
      id: map['id'],
      role: map['sender'],
      content: map['content'],
    );
  }
}
