org.gradle.jvmargs=-Xmx4g
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# Suppress Java version warnings
systemProp.org.gradle.internal.publish.checksums.insecure=true
org.gradle.warning.mode=none
