// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKOLTsCnSkNJOyKFBuKCoHr2IVlijvwuU',
    appId: '1:240516747661:web:e34a3faac6fea991b8edc4',
    messagingSenderId: '240516747661',
    projectId: 'life-ops',
    authDomain: 'life-ops.firebaseapp.com',
    storageBucket: 'life-ops.appspot.com',
    measurementId: 'G-C8YB5PM7E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApK3GhsgPbPl3IU8AC9bfBen4hZ_hF0LI',
    appId: '1:240516747661:android:924d4e04235e4d1bb8edc4',
    messagingSenderId: '240516747661',
    projectId: 'life-ops',
    storageBucket: 'life-ops.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPrOOVcKLIfMJTgJU1UZQ-21I_P44UTVw',
    appId: '1:240516747661:ios:6a1aff094bb40a24b8edc4',
    messagingSenderId: '240516747661',
    projectId: 'life-ops',
    storageBucket: 'life-ops.appspot.com',
    iosBundleId: 'com.cglendenning.lifeops',
  );
}
